export const SET_CITY_NAME = "SET_CITY_NAME";
export const FETCH_WEATHER_DATA = "FETCH_WEATHER_DATA";
export const FETCH_WEATHER_DATA_REQUEST = "FETCH_WEATHER_DATA_REQUEST";
export const FETCH_WEATHER_DATA_SUCCESS = "FETCH_WEATHER_DATA_SUCCESS";
export const FETCH_WEATHER_DATA_FAILURE = "FETCH_WEATHER_DATA_FAILURE";
